using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace StripIt
{
    /// <summary>
    /// Interaction logic for frmBugReport.xaml
    /// </summary>
    public partial class frmBugReport : Window
    {
        public frmBugReport()
        {
            InitializeComponent();

            // Set focus to command name textbox when window loads
            this.Loaded += (s, e) => CommandNameTextBox.Focus();
        }

        private void SendButton_Click(object sender, RoutedEventArgs e)
        {
            // Validate input
            if (string.IsNullOrWhiteSpace(CommandNameTextBox.Text))
            {
                System.Windows.MessageBox.Show("Please enter the command name.", "Validation Error",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                CommandNameTextBox.Focus();
                return;
            }

            if (string.IsNullOrWhiteSpace(DescriptionTextBox.Text))
            {
                System.Windows.MessageBox.Show("Please enter a description of the error.", "Validation Error",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                DescriptionTextBox.Focus();
                return;
            }

            try
            {
                SendBugReport();
                this.DialogResult = true;
                this.Close();
            }
            catch (Exception ex)
            {
                System.Windows.MessageBox.Show($"Failed to send bug report: {ex.Message}", "Error",
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void CancelButton_Click(object sender, RoutedEventArgs e)
        {
            this.DialogResult = false;
            this.Close();
        }

        private void SendBugReport()
        {
            string subject = $"Bug Report - {CommandNameTextBox.Text}";
            string body = $@"
Bug Report Details:
==================

Command Name: {CommandNameTextBox.Text}
Date/Time: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
User: {Environment.UserName}
Computer: {Environment.MachineName}

Error Description:
{DescriptionTextBox.Text}

==================
This bug report was automatically generated by the Revit Bug Report Tool.
";

            try
            {
                // Open the default email client with pre-populated fields
                string encodedSubject = Uri.EscapeDataString(subject);
                string encodedBody = Uri.EscapeDataString(body);
                string mailtoUrl = $"mailto:bim.manager@lusad.com?subject={encodedSubject}&body={encodedBody}";

                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                {
                    FileName = mailtoUrl,
                    UseShellExecute = true
                });
            }
            catch (Exception ex)
            {
                // Fallback: Copy to clipboard and show instructions
                System.Windows.Clipboard.SetText($"Subject: {subject}\n\n{body}");

                System.Windows.MessageBox.Show($"Could not open email client automatically.\n\n" +
                              $"The bug report details have been copied to your clipboard.\n" +
                              $"Please manually paste them into an email to: bim.manager@lusad.com\n\n" +
                              $"Error: {ex.Message}",
                    "Email Client Error", MessageBoxButton.OK, MessageBoxImage.Information);
            }
        }
    }
}